apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mandates.name" . }}
  labels:
    {{- include "mandates.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | int }}
  selector:
    matchLabels:
      {{- include "mandates.selectorLabels" . | nindent 6 }}
